Data validation changes
ubicomplab/rPPG-Toolbox pull request #114
Opened 2023-01-19 09:00 UTC by yahskapar

This PR makes two key changes:

1. Each trainer is modified such that code related to the validation dataset and model selection is NOT executed when USE_LAST_EPOCH is set to True.
2. Main.py and config.py are modified to better indicate to users whether or not the validation dataset matters and to catch any weird behavior a user may encounter if they modify their configuration file incorrectly.

I don't think the config (YAML) files themselves have to be updated, especially since any additional functionality related to using a validation dataset (e.g., preprocessing, loading) should only ever occur if a validation dataset is actually being used for model selection in subsequent testing.

2023-01-19 09:02 UTC, yahskapar commented on main.py
> +        if config.VALID.DATA.DATASET is not None:
I repeated this pattern for config.TRAIN... and config.TEST... below just to make things look a bit cleaner (and since it makes sense as an additional guard if no dataset type was specified).

2023-01-19 17:29 UTC, xliucs reviewed
Pleae address my comments.

2023-01-19 17:29 UTC, xliucs commented on main.py
> +        if config.VALID.DATA.DATASET is not None:
I think we should do `config.TRAIN.DATA.DATASET is not None and config.TRAIN.DATA.DATA_PATH`

2023-01-19 17:29 UTC, xliucs commented on config.py
> +            raise ValueError(self.name, 'Validation dataset is not provided despite USE_LAST_EPOCH being False!')
Can you combine these two if statements? Also, it is preferred to use `not config.TEST.USE_LAST_EPOCH and not config.VALID.DATA.DATASET`

2023-01-19 17:29 UTC, xliucs commented on config.py
> +            raise ValueError(self.name, 'Validation dataset is not provided despite USE_LAST_EPOCH being False!')
Probaby double check if `config.VALID.DATA.DATASET is None` == `not config.VALID.DATA.DATASET`

2023-01-19 17:29 UTC, xliucs commented on neural_methods/trainer/DeepPhysTrainer.py
> +                valid_loss = self.valid(data_loader)
Change to not instead of using `== False`

2023-01-19 17:29 UTC, xliucs commented on neural_methods/trainer/EfficientPhysTrainer.py
> +            print("best trained epoch:{}, min_val_loss:{}".format(self.best_epoch, min_valid_loss))
same

2023-01-19 17:29 UTC, xliucs commented on neural_methods/trainer/EfficientPhysTrainer.py
> +                valid_loss = self.valid(data_loader)
same

2023-01-19 17:29 UTC, xliucs commented on neural_methods/trainer/EfficientPhysTrainer.py
> +            min_valid_loss = 1
same

2023-01-19 17:41 UTC, yahskapar commented on config.py
> +                            Please turn DO_PREPROCESS to False or delete existing FILE_LIST_PATH .csv file.')
Nope, just indented it and added the if statements immediately prior to this chunk of code.

2023-01-19 18:34 UTC, yahskapar commented on config.py
> +            raise ValueError(self.name, 'Validation dataset is not provided despite USE_LAST_EPOCH being False!')
> Can you replace all the `self.name` to `self.dataset_name`? We have changed that naming convention in base dataloader.

I replaced these with string literals instead since get_config, and subsequently the function to update the config, are only called once and aren't passed the dataset name as is done in the base dataloader.

2023-01-19 19:54 UTC, yahskapar commented on neural_methods/trainer/DeepPhysTrainer.py
> +            min_valid_loss = 1
This seems to just be an initial value for this chunk of code later on in the train() function:

```
                if (valid_loss < min_valid_loss) or (valid_loss < 0):
                    min_valid_loss = valid_loss
                    self.best_epoch = epoch
                    print("Update best model! Best epoch: {}".format(self.best_epoch))
                    self.save_model(epoch)
```

My current understanding is as follows:

- For TS-CAN, EfficientPhys, and DeepPhys, which all use MSE loss, the first term in the if statement is utilized to set the initial min_valid_loss value. If it's less than the initialized value of 1, it's set to to the new value and a new best epoch is found. The MSE loss can never be negative, so the second term should never be triggered. The assumption here seems to be that the valid loss has to get below 1 to be updated as the best epoch for the first time. @xliucs, maybe this can be changed such that `current_valid_loss` is used, set to `None` to begin with, and when updated for the first time we check if's `None`, set it if so, and use it moving forward as the min_valid_loss.
- For PhysNet, which uses a negative Pearson correlation loss, the second term (valid_loss < 0) is triggered to set the initial min_valid_loss. Subsequently, as the negative Pearson correlation loss becomes more negative, the best epoch is updated.

2023-01-19 20:08 UTC, yahskapar commented on neural_methods/trainer/DeepPhysTrainer.py
> +            min_valid_loss = 1
I just updated this PR with a commit (0b0b8d4dfaeb52b3897c559530abcf6e8b784570) that I believe makes more sense. Let me know what you think, @xliucs.

2023-01-19 23:54 UTC, xliucs requested changes

2023-01-19 23:54 UTC, xliucs commented on main.py
> +                raise ValueError("Validation dataset not specified despite USE_LAST_EPOCH set to False!")
@yahskapar  Can you address this one?

2023-01-20 00:01 UTC, yahskapar commented on main.py
> +                raise ValueError("Validation dataset not specified despite USE_LAST_EPOCH set to False!")
Done.

2023-01-20 00:06 UTC, xliucs approved these changes
LGTM

2023-01-20 00:06 UTC, merged