Use rindex instead of index for split_idx
ubicomplab/rPPG-Toolbox pull request #125
Opened 2023-02-03 03:51 UTC by yahskapar

As the title suggests. I think this makes more sense than how it currently is based on [how input files get saved in the first place](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/dataset/data_loader/BaseLoader.py#L326). `rindex` basically finds the last occurrence of a specified value. Since input{chunk_id} is guaranteed to be at the end of the input filename, `rindex` makes more sense to use in case a passed in item_path_filename ever had more than one `_` in it and `index` returned an erroneous `split_idx` because it just happened to find the `_` in something like `subject_c`.

2023-02-03 04:59 UTC, xliucs requested changes
Can you add a comment on this line of code to give some concrete exampels such as real filenames? I think this is not well documented.  

Also, have you tried this with other datasets?  You can just test on some very small pure/ubfc toy datasets if you like.

2023-02-03 06:45 UTC, yahskapar commented
Tested with PURE_UNSUPERVED.yaml and everything appears to be ok. Also verified that printing out certain variables in the BaseLoader made sense.

2023-02-03 07:59 UTC, yahskapar commented
@xliucs updated the commit with some comments that are a bit verbose, but hopefully they're helpful.

2023-02-05 07:17 UTC, xliucs approved these changes
LGTM

2023-02-05 07:17 UTC, merged