update MMPD
ubicomplab/rPPG-Toolbox pull request #134
Opened 2023-03-27 01:39 UTC by McJackTang

enable label choose

2023-03-27 04:55 UTC, xliucs requested changes
Can you please provide some sample results for at least one training / inference results? Also please consider adding pre-trained models. Thanks.

2023-03-27 04:55 UTC, xliucs commented on configs/infer_configs/PURE_UNSUPERVISED.yaml
> +    DATA_PATH: "/data1/acsp/toolbox_data/PURE/RawData"           # Raw dataset path, need to be updated
revert them back.

2023-03-27 04:55 UTC, xliucs commented on configs/infer_configs/PURE_UNSUPERVISED.yaml
> +    CACHED_PATH: "/data/rPPG_dataset/processed_dataset_makeup"   # Processed dataset save path, need to be updated
same

2023-03-27 04:55 UTC, xliucs commented on dataset/data_loader/BaseLoader.py
> +            '/data/rPPG-Toolbox_MMPD/dataset/haarcascade_frontalface_default.xml')
Don't change it.

2023-03-28 10:49 UTC, McJackTang commented
METHODS | MAE | RMSE | MAPE | PEARSON
TS-CAN(PURE_MMPD(simplest)) | 1.78 | 3.57 | 2.47 | 0.93
TS-CAN(UBFC__MMPD(simplest)) | 1.46 | 3.13 | 2.04 | 0.94

2023-04-10 06:01 UTC, yahskapar requested changes
Left a few comments that I think should be addressed prior to merging. Also, I'm a bit confused by the general approach with settings in the config files on second glance...for something like motion I see what's below:

```
MOTION: [1, 2, 3, 4] # 'Stationary', 'Rotation', 'Talking', 'Walking'
```
Why can't this be the following...
```
MOTION: ['Stationary', 'Rotation', 'Talking', 'Walking']
```
So that the setting is practically self-explanatory without the comment? Similarly for things like GENDER, why use 1 and 2 instead of just Male and Female? For GLASSES, why 1 and 2 instead of just True or False? I feel like the usage of numbers here, except in the case of SKIN_COLOR, doesn't really make sense.

2023-04-10 06:17 UTC, McJackTang commented on config.py
> +_C.TRAIN.DATA.INFO.GLASSER = [True]
Thanks for advice. For the label settings, we used to set as what you recommended but this is more accessible for users with less input. For typo, we define the glasser as the person who wears glasses, and this is due to our dataset labels which has already be shared.

2023-04-10 06:19 UTC, McJackTang commented on configs/train_configs/UBFC_UBFC_MMPD_TSCAN_BASIC.yaml
> +TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
thanks for reminding for the config setting

2023-04-10 06:26 UTC, McJackTang commented on configs/train_configs/MMPD_MMPD_UBFC_TSCAN_BASIC.yaml
> +  EPOCHS: 20
Yeah we have changed that for quicker training. I would change this back. Thanks

2023-04-10 06:30 UTC, McJackTang commented on configs/train_configs/SCAMPS_SCAMPS_MMPD_TSCAN_BASIC.yaml
Sure I would check it. Thanks!

2023-04-10 06:52 UTC, McJackTang commented on config.py
> +_C.TRAIN.DATA.INFO.GLASSER = [True]
Furthermore, the digital numbers of labels have benefit for our file filter. Considering all aspects, I may suggest maintaining the settings of labels and glasser.

2023-04-13 04:07 UTC, yahskapar requested changes
Some small changes I think you should make and a few fixes - thank you for your work on this PR and responding to my feedback!

2023-04-13 04:07 UTC, yahskapar commented on dataset/data_loader/MMPDLoader.py
> +        if information[2] == 'True' or information[2] == True:
For all of the cases here and below where we are evaluating True or False, why do we check for both the string 'True' and the Boolean True? Shouldn't we just check for one of the two?

In the case of MMPD, it looks like it's evaluating a string 'True' or 'False', so just check for that.

2023-04-13 05:05 UTC, McJackTang commented
Thanks for all the suggestions. Really appreciate  it.
I will fix the bugs and typos according  to your advice and the convience of all users.

2023-04-13 05:07 UTC, yahskapar commented on configs/train_configs/SCAMPS_SCAMPS_MMPD_TSCAN_BASIC.yaml
> +    DATA_FORMAT: NCDHW
Change this back to NDCHW

2023-04-26 17:07 UTC, yahskapar approved these changes
Looks good to me. There's still a few places where there appears to be extra single spacing or tab spacing after something like the character string "180" or at the very end of the line. This is very minor, so I'll still go ahead and approve.

Please also be sure to give your code one more quick test by trying out the configs and posting the results here before merging. Thanks!

2023-04-27 11:56 UTC, McJackTang commented
PURE_PURE_MMPD_tscan results: 
FFT MAE (FFT Label):2.1197150735294117
FFT RMSE (FFT Label):4.945881743008046
FFT MAPE (FFT Label):2.8992430306314922
FFT Pearson (FFT Label):0.885015925039581

MMPD INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False

2023-04-27 11:57 UTC, merged