iBVP dataset, iBVPNet model and MACC evaluation metrics
ubicomplab/rPPG-Toolbox pull request #262
Opened 2024-04-09 18:15 UTC by jnj256

Dear rPPG-Toolbox team,

Below we summarize our contributions that have been published in our recent work on [iBVP dataset](https://www.mdpi.com/2079-9292/13/7/1334).

Through our work, we primarily contribute a novel rPPG dataset, which we refer to as 'iBVP dataset'. Additionally, we introduce iBVPNet model, which was found to be an effective 3D-CNN architecture, with results presented in the paper. We further discover the use of maximum amplitude of cross-correlation (MACC) as highly suitable evaluation metrics to validate rPPG methods.

Researchers will be able to access our dataset by referring to the details mentioned on this [GitHub page](https://github.com/PhysiologicAILab/iBVP-Dataset).

Our code builds upon the [rPPG-Toolbox](https://github.com/ubicomplab/rPPG-Toolbox) repo, and all the contributions from our side can be found [in this forked repo](https://github.com/PhysiologicAILab/rPPG-Toolbox). We would like to create a pull request to merge our contributions. For the same, we summarize the key changes below, and provide a link for detailed [difference log](https://github.com/ubicomplab/rPPG-Toolbox/compare/main...PhysiologicAILab:rPPG-Toolbox:main).

**Added:**
* dataset/data_loader/IBVPLoader.py: For loading RGB video frames of iBVP dataset
* neural_methods/model/iBVPNet.py: The iBVPNet model introduced in our work
* neural_methods/trainer/iBVPNetTrainer.py: Trainer for iBVPNet
* "train" and "infer" configs for iBVP dataset as well as iBVPNet model

**Updated:**
* dataset/data_loader/__init__.py: Added import statement for IBVPLoader
* neural_methods/trainer/__init__.py: Added import statement for IBVPNet
* evaluation/metrics.py: Updated for MACC evaluation metrics
* evaluation/post_process.py: Updated for MACC evaluation metrics
* unsupervised_methods/unsupervised_predictor.py: Updated for MACC evaluation metrics
* main.py: Added support for iBVPNet model
* config.py: Updated for iBVPNet model
* setup.sh: Updated to make the installation work with Ubuntu 20.04 (can be ignored while merging)
* ReadMe: Added details of the iBVP dataset and iBVPNet model

Please do let us know if there is anything that we can further provide to help you evaluate our contributions before merging.

2024-04-26 11:03 UTC, jnj256 commented
> I will get to testing and reviewing this PR fully by this weekend @jnj256 - sorry for the wait!

Thanks Akshay for the update. 
I identified few refinements for which I shall raise a separate PR later, as these should not affect your testing. For e.g., at line 139 of metrics.py, there should be no unit for MACC ("dB" needs to be removed).

2024-04-29 07:12 UTC, yahskapar requested changes
Hi @jnj256,

Fairly minor comments, and many of the changes I requested should be quick. Should be good to go after addressing those, and I look forward to the additional PR you mentioned with some other changes.

2024-04-29 07:12 UTC, yahskapar commented on configs/infer_configs/IBVP_PURE_IBVPNET_BASIC.yaml
> +  MODEL_PATH: "./final_model_release/IBVP_iBVPNet_diffnormalized.pth"
Small nitpick, rename the model file itself to have the "i" in "iBVP" consistently lowercase. As in, it should be "iBVP_iBVPNet".

2024-04-29 07:12 UTC, yahskapar commented on configs/infer_configs/IBVP_PURE_IBVPNET_BASIC.yaml
> +  MODEL_PATH: "./final_model_release/IBVP_iBVPNet_diffnormalized.pth"
If you change this, be sure to change this across all config files after updating the model name in the final_model_release folder.

2024-04-29 07:12 UTC, yahskapar commented on configs/infer_configs/PURE_UNSUPERVISED.yaml
> +    DO_PREPROCESS: True               # if first time, should be true
Undo this change

2024-04-29 07:12 UTC, yahskapar commented on configs/infer_configs/PURE_UNSUPERVISED.yaml
> +    DATA_PATH: "data/PURE_Dataset/raw"                     # Raw dataset path, need to be updated
Undo these changes as well

2024-04-29 07:12 UTC, yahskapar commented on configs/infer_configs/UBFC-rPPG_UNSUPERVISED.yaml
> +    DO_PREPROCESS: True               # if first time, should be true
Undo

2024-04-29 07:12 UTC, yahskapar commented on configs/infer_configs/UBFC-rPPG_UNSUPERVISED.yaml
> +    DATA_PATH: "data/UBFC-rPPG/data"                     # Raw dataset path, need to be updated
Undo

2024-04-29 07:12 UTC, yahskapar commented on evaluation/metrics.py
> +                print("MACC: {0} +/- {1} (dB)".format(MACC_avg, standard_error))
I know you mentioned you'd remove dB in another PR, but maybe consider doing it here alongside the other small config-related changes I suggested.

2024-04-29 07:12 UTC, yahskapar commented on main.py
> +        elif config.TRAIN.DATA.DATASET == "IBVP":
Consider changing this, and other instances of this elsewhere, from IBVP to iBVP for consistency.

2024-04-29 07:12 UTC, yahskapar commented on setup.sh
> +conda create -n rppg-toolbox python=3.8 pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge -q -y
I'm a little hesitant to allow this change to go through - can you remind me why exactly you had to do this in order to get this to work on your version of Ubuntu? FWIW, I also use Ubuntu 20.04 and haven't run into any issues with the original environment creation command.

2024-04-29 07:12 UTC, yahskapar commented on setup.sh
> +conda create -n rppg-toolbox python=3.8 pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge -q -y
Was it something specific to code that you added (e.g., related to the iBVPNet model)?

2024-04-29 16:07 UTC, jnj256 commented on setup.sh
> +conda create -n rppg-toolbox python=3.8 pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge -q -y
This must have been related to driver versions, which are following for me: 
Driver Version: 530.30.02    CUDA Version: 12.1
And therefore, the corresponding cudatoolkit (cudatoolkit=11.6) was required for installation. 
However, given your comment, I've reverted this change.

2024-04-29 16:09 UTC, jnj256 commented
@yahskapar : Thank you for going through all the changes made and for your suggestions. I've now addressed your comments and suggestions. Please have a look if everything looks good to go.

2024-04-29 16:55 UTC, yahskapar approved these changes
LGTM, thanks!

2024-04-29 16:57 UTC, yahskapar commented
@jnj256, looks like there's some conflicts, probably because of the OMIT PR that was merged recently. Can you pull those changes and make sure to resolve any conflicts? You should be good to squash and merge after that - thanks again for your contribution!

2024-04-29 17:09 UTC, jnj256 commented
@yahskapar : Thanks for your quick review of the changes. About the conflict related to OMIT PR, I've now resolved it.

2024-04-29 17:10 UTC, merged