Add PhysMamba
ubicomplab/rPPG-Toolbox pull request #326
Opened 2024-10-29 11:41 UTC by gauthier-th

This PR adds the PhysMamba model to rPPG-Toolbox.

From [PhysMamba: Efficient Remote Physiological Measurement with SlowFast Temporal Difference Mamba](https://doi.org/10.48550/arXiv.2409.12031), by Luo *et al.*, 2024

2024-10-29 12:31 UTC, yahskapar commented
Thanks @gauthier-th - one of us will try to take a deep look sometime soon. On first glance, I do wonder if this PR can be simplified a fair bit by removing anything that isn't strictly needed for PhysMamba (e.g., any additional documentation, libraries that aren't explicitly used in PhysMamba but present for general SSM architectures).

I can give specific recommendations on what may be removable once I take a deeper look, but perhaps you can take another pass before I or someone else gets to reviewing this just to make the reviewing workload a bit easier. Thanks again.

2024-10-29 13:50 UTC, gauthier-th commented
Thanks for you reply.

As requested, I removed some unnecessary changes.

However, I left the files from the `mamba-ssm` library because this is a modified version of [mamba-ssm](https://github.com/state-spaces/mamba) originating from [the code of the authors of PhysMamba](https://github.com/Chaoqi31/PhysMamba).

2024-11-01 23:19 UTC, yahskapar requested changes
Thanks for this great PR! Check out my comments, I believe most of them are very minor or are more along the lines of questions.

2024-11-01 23:19 UTC, yahskapar commented on README.md
> +  - [PhysMamba: Efficient Remote Physiological Measurement with SlowFast Temporal Difference Mamba](https://doi.org/10.48550/arXiv.2409.12031), by Luo *et al.*, 2024
One significant thing to note - there appear to be two PhysMamba papers, one by you that's being proposed to be added to this repo and one by other authors [here](https://arxiv.org/pdf/2408.01077). Yours appears to be accepted to a conference, has reasonable results, and also includes Zitong Yu who was the author of PhysNet, so I'm happy to push for it to be included in the repo. I do wonder if there's some way we can better distinguish your approach from the other PhysMamba's approach though - maybe by commenting on how your approach may be more efficient and scalable across longer sequences? 

Alternatively, if you think the other paper is not worth even mentioning, I would be curious to know why (it's not cited in your paper either).

2024-11-01 23:19 UTC, yahskapar commented on README.md
> +STEP 4: `bash install.sh`
Can you either integrate this and step 3 into its own bash script so that it's one step, or perhaps renaming this shell script to be `additional_setup.sh`?

2024-11-01 23:19 UTC, yahskapar commented on install.sh
As I mentioned before, try integrating this shell scripts contents into a single unified shell script or renaming this as `additional_setup.sh`. It may make sense to do the latter in case, after installing the more general pip requirements, there's any additional, tool-specific setup that needs to be done.

2024-11-01 23:19 UTC, yahskapar commented on neural_methods/trainer/PhysMambaTrainer.py
> +"""PhysNet Trainer."""
Correct this to be PhysMamba Trainer.

2024-11-01 23:19 UTC, yahskapar commented on neural_methods/trainer/PhysMambaTrainer.py
> +
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on neural_methods/trainer/__init__.py
> +import neural_methods.trainer.PhysMambaTrainer
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on requirements.txt
> +causal-conv1d==1.0.0
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on setup.sh
> +conda create -n rppg-toolbox python=3.8 pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 pytorch-cuda=12.1 -c pytorch -c nvidia -q -y
This should be ok, but out of curiosity, what hardware (e.g., GPU) did you test this with? Can you verify this hasn't affected a few other models in the repo (e.g., no conflicts when trying to run TS-CAN)?

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/.gitignore
> +mamba_ssm.egg-info/
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_bwd_fp32_real.cu
> +template void selective_scan_bwd_cuda<float, float>(SSMParamsBwd &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_bwd_fp32_complex.cu
> +template void selective_scan_bwd_cuda<float, complex_t>(SSMParamsBwd &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_bwd_fp16_real.cu
> +template void selective_scan_bwd_cuda<at::Half, float>(SSMParamsBwd &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_bwd_fp16_complex.cu
> +template void selective_scan_bwd_cuda<at::Half, complex_t>(SSMParamsBwd &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_bwd_bf16_real.cu
> +template void selective_scan_bwd_cuda<at::BFloat16, float>(SSMParamsBwd &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_bwd_bf16_complex.cu
> +template void selective_scan_bwd_cuda<at::BFloat16, complex_t>(SSMParamsBwd &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_fwd_bf16.cu
> +template void selective_scan_fwd_cuda<at::BFloat16, complex_t>(SSMParamsBase &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_fwd_fp16.cu
> +template void selective_scan_fwd_cuda<at::Half, complex_t>(SSMParamsBase &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-01 23:19 UTC, yahskapar commented on tools/mamba/csrc/selective_scan/selective_scan_fwd_fp32.cu
> +template void selective_scan_fwd_cuda<float, complex_t>(SSMParamsBase &params, cudaStream_t stream);
Correct the end of this file so that there is a proper newline at the end, this might be something specific to your code editor.

2024-11-04 09:50 UTC, gauthier-th commented on README.md
> +STEP 4: `bash install.sh`
I moved the `pip install -r requirements.txt` command into the `install.sh` script

2024-11-04 10:23 UTC, gauthier-th commented on setup.sh
> +conda create -n rppg-toolbox python=3.8 pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 pytorch-cuda=12.1 -c pytorch -c nvidia -q -y
I tested it with a Nvidia RTX 3060 with Cuda 12.5 and with a Nvidia 4090 with Cuda 12.2.
I just checked and it's running fine with TS-CAN, PhysNet and DeepPhys.

2024-11-04 10:28 UTC, gauthier-th commented
Fixed the install script, the issue with newline at the end of the files and the typo.

2024-11-04 12:56 UTC, yahskapar approved these changes
LGTM - thanks for your contribution!

2024-11-04 12:56 UTC, merged