Pipeline v4: Formalized Cross Dataset training&testing
ubicomplab/rPPG-Toolbox pull request #51
Opened 2022-07-15 01:00 UTC by zyzzzz-123

① you can choose "train_and_test" or "only_test" in yaml. if  "train_and_test", it will train firstly and then use the trained model to test; if "only_test", it will use the pre-trained model to test.
②you can set the parameters of train valid test datasets individually.
③delete evalution_config  some other changes in config to fit the changes of yaml format.
④tscan_trainer and deeppyhs_trainer are updated, but other trainers are kept the same as before. (will be updated in future)

To replicate my result, you can run it with PURE_TSCAN_BASIC.yaml and will get:
best_epoch:  4
loss: 0.6788842607289552
FFT MAE:4.200105773870969
Peak MAE:2.5538677355174695
FFT MAE (Peak Label):4.462451860154304
Peak MAE (Peak Label):1.7392284047725766
FFT MAE (FFT Label):1.1340725806451613
Peak MAE (FFT Label):4.849251368561001

2022-07-15 17:59 UTC, xliucs requested changes

2022-07-15 17:59 UTC, xliucs commented on config.py
> +_C.TRAIN.DATA.PREPROCESS.LARGE_FACE_BOX = True
add a comment to explain what is LARGE_FACE_BOX.

2022-07-15 17:59 UTC, xliucs commented on config.py
> +_C.TRAIN.DATA.PREPROCESS.LARGER_BOX_SIZE = 1.5
SAME as BOX SIZE.

2022-07-15 17:59 UTC, xliucs commented on config.py
> +_C.TRAIN.DATA.PREPROCESS.W = 128
Actually, let us add a comment to explain every parameter in _C.TRAIN.DATA.PROCESS, but let me help you with these changes.

2022-07-15 17:59 UTC, xliucs commented on config.py
> +#
If we don't we need these comments, please remove them.

2022-07-15 17:59 UTC, xliucs commented on config.py
> +    # if args.cached_path:
same here.

2022-07-15 17:59 UTC, xliucs commented on config.py
> +    # if args.preprocess:
remove

2022-07-15 17:59 UTC, xliucs commented on dataset/data_loader/BaseLoader.py
> +        for idx in range(det_num):
same here. some comments to explain your for loop would be helpful.

2022-07-15 17:59 UTC, xliucs commented on dataset/data_loader/BaseLoader.py
> +        print(self.cached_path)
if you don't need print this, remove it.

2022-07-16 11:00 UTC, zyzzzz-123 commented on neural_methods/trainer/TscanTrainer.py
> +    # def test(self, data_loader):
already deleted.

2022-07-16 11:05 UTC, zyzzzz-123 commented on config.py
> +    # if args.cached_path:
removed.

2022-07-16 11:06 UTC, zyzzzz-123 commented on config.py
> +#
removed.

2022-07-16 11:13 UTC, zyzzzz-123 commented on configs/PURE_DEEPPHYS_BASIC.yaml
> +#  MODEL_PATH:  "/data1/acsp/Yuzhe_Zhang/Toolbox_master_2/rPPG-Toolbox/PreTrainedModels/PURE_SizeW72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized_Large_boxTrue_Large_size
removed.

2022-07-16 11:14 UTC, zyzzzz-123 commented on configs/UBFC_TSCAN_BASIC.yaml
> +        #MODEL_PATH: # if TRAIN_OR_TEST:"train_and_test", should be "" or anything, it will use currently trained model.
removed.

2022-07-16 11:16 UTC, zyzzzz-123 commented on dataset/data_loader/BaseLoader.py
> +        # self.cached_path = os.path.join(config_data.CACHED_PATH, name)
removed.

2022-07-16 11:42 UTC, zyzzzz-123 commented on dataset/data_loader/BaseLoader.py
>      def resize(self, frames, danymic_det, det_length,
added. Can you review these comments, please? I' 'm worried that they are not clear enough.

2022-07-16 11:42 UTC, zyzzzz-123 commented on dataset/data_loader/BaseLoader.py
> +        for idx in range(det_num):
I have added some comments. Please review them.

2022-07-16 11:43 UTC, zyzzzz-123 commented on dataset/data_loader/BaseLoader.py
> +        print(self.cached_path)
removed.

2022-07-16 12:08 UTC, zyzzzz-123 commented on neural_methods/trainer/DeepPhysTrainer.py
> +            # if config.NUM_OF_GPU_TRAIN > 1:
removed.

2022-07-16 12:48 UTC, zyzzzz-123 commented
The latest commit fixes the dataset load error detection problem, it will assert an error if the data_path is not true.

2022-07-16 14:34 UTC, zyzzzz-123 commented
①I formalize yamls about  deeppyhs and tscan and do some testing experiment using these yanls.
You can refer to https://www.notion.so/pipeline_v4-experiment-document-02463b14111e44e1b0518ebbce07ac19 to see specific results and replicate them.
② delete some useless files. Adds and deletes some comments.
③ there seems to be no need to maintain evaluation_neural_method.py, delete it or not?
Some problems:
1.deepphys training results change when num_of_GPU changes, it seems to have a bug.
2.tscan doesn’t support multi-gpu right now.
3.It seems that when testing on UBFC, although using **different trained models** and **different preprocessing methods**(previous experiments, not here), the results are partially the same.
I am still working on visualizing it to figure out whether some bugs account for it or it’s just a unique attribute of UBFC.

2022-07-17 04:57 UTC, xliucs approved these changes
LGTM

2022-07-17 04:58 UTC, merged