Multi scamps new
ubicomplab/rPPG-Toolbox pull request #60
Opened 2022-08-05 07:37 UTC by zyzzzz-123

Actually there are many commits ahead of the main branch. 
Sorry about it. It's mainly because it needs more time to do testing experiments than improve some problems. So I always made some new changes before getting a result.

1. Delete useless command line control parameters in main and config.py (only yaml file is left)
2.  Set an upper limit on the number of running processes for multithreading
	(for pure/ubfc/scamps)
3.  Update output format (delete labeled items)
4.  Fix a bug about multi-gpu TSCAN training
5. Changed the way of appending data_path when preprocessing to ensure reproductivity
(Now the results will be the same between DO_PROCESSS: True and False)
6. delete useless yaml files
7. fix "dataloader" name conlict in main_neural_method.py
8. fix using "assert" wrongly problem.

Here are some results:
1.PURE_PURE_UBFC_TSCAN_BASIC   MAE fft ( fft label)  :0.992
2.PURE_PURE_UBFC_DEEPPHYS_BASIC MAE fft ( fft label)  :1.021
3.UBFC_UBFC_PURE_TSCAN.BASIC MAE fft ( fft label)  :5.75
4.UBFC_UBFC_PURE_DEEPPHYS.BASIC MAE fft ( fft label)  : 5.80

2022-08-05 22:39 UTC, xliucs requested changes

2022-08-05 22:39 UTC, xliucs commented on configs/PURE_PURE_UBFC_PHYSNET_STANDARDIZED_BASIC.yaml
> +#      LABEL_TYPE: Raw
remove them if you don't need.

2022-08-05 22:39 UTC, xliucs commented on configs/PURE_PURE_UBFC_PHYSNET_STANDARDIZED_BASIC.yaml
> +#  "/data1/acsp/Yuzhe_Zhang/Toolbox_master_2/rPPG-Toolbox/PreTrainedModels/PURE_SizeW128_SizeH128_ClipLength128_DataTypeStandardized_LabelTypeStandardized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_
same

2022-08-05 22:39 UTC, xliucs commented on configs/SCAMPS_SCAMPS_UBFC_PHYSNET_BASIC.yaml
> +                    # if TRAIN_OR_TEST:"only_test", should be "path"
same as above

2022-08-05 22:39 UTC, xliucs commented on configs/SCAMPS_SCAMPS_UBFC_PHYSNET_STANDARDIZED_BASIC.yaml
> +                    # if TRAIN_OR_TEST:"only_test", should be "path"
do you need these?

2022-08-05 22:39 UTC, xliucs commented on main_neural_method.py
> +# os.environ["CUDA_VISIBLE_DEVICES"] = "2"
i thought it should be 0?

2022-08-05 22:39 UTC, xliucs commented on main_neural_method.py
> +    # PURE_PURE_UBFC_PHYSNET_NORMARLIZED_BASIC.yaml
If you want to keep a list here, maybe make it looks better. Like 
''' Sample Yaml List
    SCAMPS_SCAMPS_UBFC_TSCAN_BASIC.yaml
    SCAMPS_SCAMPS_UBFC_DEEPPHYS_BASIC.yaml
'''

2022-08-05 22:39 UTC, xliucs commented on metrics/metrics.py
> +            print('Pred HR peak: ', pred_hr_peak)
I think it is just for debugging purpose. Don't need to include these if necessary. Also threshold of 1 is too small.

2022-08-06 02:38 UTC, zyzzzz-123 commented on configs/SCAMPS_SCAMPS_UBFC_PHYSNET_STANDARDIZED_BASIC.yaml
> +                    # if TRAIN_OR_TEST:"only_test", should be "path"
they are comments actually.

2022-08-06 03:42 UTC, merged